[build]
  command = "cd momentum-ai-universal && npm install --legacy-peer-deps --force && npm run web:build"
  publish = "momentum-ai-universal/dist"

[build.environment]
  EXPO_PUBLIC_SUPABASE_URL = "https://nsgqhhbqpyvonirlfluv.supabase.co"
  EXPO_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZ3FoaGJxcHl2b25pcmxmbHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTY1NTgsImV4cCI6MjA2NTMzMjU1OH0.twGF9Y6clrRtJg_4S1OWHA1vhhYpKzn3ZpFJPGJbmEo"
  GROQ_API_KEY = "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"
  NODE_ENV = "production"
  SKIP_PREFLIGHT_CHECK = "true"

# Expo web build configuration
[build.processing]
  skip_processing = false

# Headers for SPA routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 